dist: trusty
language: java
jdk:
- oraclejdk8
env:
  global:
    script: mvn clean verify
after_script:
  - echo "after_script start"
  - curl https://raw.githubusercontent.com/jvandenbossche/ContrastTravisVerify/master/ContrastTravisVerify.sh -o ./ContrastTravisVerify.sh
  - bash ./ContrastTravisVerify.sh -e || travis_terminate 1;