echo "SCRIPT EXECUTION IS WORKING"
CONTRAST_USERNAME=sourabh.katti@contrastsecurity.com
CONTRAST_URL=https://apptwo.contrastsecurity.com/Contrast/
CONTRAST_SERVICE_KEY=ZAXHB4LTKMH25NQ1
CONTRAST_API_KEY=KpAoBf7Plj71LFl4ihODRX8CgFh8hyO8
CONTRAST_ORG_ID=f7ea7169-d4eb-42c4-b32e-5c0ea0ca9733

echo $CONTRAST_USERNAME
echo $CONTRAST_URL
echo $CONTRAST_SERVICE_KEY
echo $CONTRAST_API_KEY
echo $CONTRAST_ORG_ID
